config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'

  get '/most_popular_treatment/treatments/:id', to: 'treatments#show', as: 'most_popular_treatment'
 
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients, except: [:edit, :update, :destroy] do
    resources :appointments
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews, only: [:index]
  end
  
  resources :reviews, only: [:index, :new, :create] #shallow: true

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/treatment.rb
class Treatment < ApplicationRecord

    has_many :appointments
    has_many :clients, through: :appointments 

    def self.most_popular_treatment
        treatment_id = Appointment.group(:treatment_id).count.max_by { |k, v| v}[0]
        self.find(treatment_id)
    end 
    
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

    def index 
        @treatment = Treatment.all.most_popular_treatment
    end 

    def show
        @treatment = Treatment.find(params[:id])
    end 

    private 

    def treatment_params
        params.require('treatment').permit(:title, :price, :duration, :description)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/index.html.erb
   <div class="container">
        <div class="row justify-content-center">
            <h1>OUR TREATMENTS</h1>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <% Treatment.all.each do |treatment| %>
                <ul>
                    <%= link_to treatment.title, treatment_path(treatment) %></a>
                </ul>
            <% end %>
        </div>
    </div>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <img src="/assets/massage.jpg" class="float-left" alt="Paris" width="390" height="300"> 
            </div>
            <div class="col-sm-4">
                <img src="/assets/wood_therapy.jpeg" class="float-right" width="450" height="300">
            </div>
            <div class="col-sm-4">
                <img src="/assets/facial_1.jpeg" class="float-right" alt="Paris" width="435" height="300">
            </div>
        </div>
    </div>
<br>

    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <img src="/assets/spa_tub.JPG" class="mx-auto d-block" style="width:50%">
            <h4></h4>
            <p>Exclusive beauty and wellness, treatments with trusted hands bring locals together for the most lux lifestyle trends.</p>
            <p> Our handcrafted practices, focuses on the healing properties of Sea, Salt, Sand, and Sound.
                Sea promises an escape from reality with blue mineral oils that help muscles relax and heal.
                Salt balances energy with well-being properties that calm nerves and soothe muscles.
                Sand warms the body for decadent comfort while stimulating the skin’s reflexes.
                Sound from Tingsha bells set the tempo for the ultimate balance of mind, body, and soul.

                <p><h5>Our most popular treatment is 
                    "<%= link_to Treatment.most_popular_treatment.title, most_popular_treatment_path(@treatment) %>"</h5>
                </p>
            </p>
        </div>
    </div>
</div>
    
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <a class="btn btn-secondary" <%= link_to "Book a Appointment »", new_appointment_path %></a>
        </div>
    </div>
</div>

app/views/treatments/show.html.erb
<div class="container">
        <div class="row">
            <ul>
                <h4><%= @treatment.title %></h4> <br>
                <%= @treatment.price %> |
                <%= @treatment.duration %> <br>
                <%= @treatment.description %> <br><br><br>
                <%= image_tag '/assets/treat_baner.jpg' %>
            </ul>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <a class="btn btn-secondary" <%= link_to "Book a Appointment »", new_appointment_path %></a>
            </div>
        </div>
    </div>
<br>
      <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <img src="/assets/salt_facial.jpg" class="float-left" alt="Paris" width="390" height="300"> 
            </div>
            <div class="col-sm-4">
                <img src="/assets/lashes_2.jpeg" class="float-right" width="450" height="300">
            </div>
            <div class="col-sm-4">
                <img src="/assets/sand.jpg" class="float-right" alt="sand" width="450" height="300">
            </div>
        </div>
    </div>

    