config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'

  get '/most_popular_treatment/treatments/:id', to: 'treatments#show', as: 'most_popular_treatment'
 
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients, except: [:edit, :update, :destroy] do
    resources :appointments
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews, only: [:index]
  end
  
  resources :reviews, only: [:index, :new, :create] #shallow: true

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

    has_secure_password

    has_many :reviews
    has_many :appointments
    has_many :treatments, through: :appointments 
    has_many :reviewed_appointments, through: :reviews, source: :appointments 

    validates_presence_of :first_name, :last_name, format: { with: /\A[a-zA-Z]+\Z/ }, message:"Cannot be blank"
    validates :email, format: {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, uniqueness: {message:"already belongs to an existing account"}

    def self.appointments_status
        joins(:appointments).where("appointments.created_at < ?", Time.now)
    end

    def to_s
        self.first_name + " " + self.last_name
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

    before_action :is_logged_in?
    before_action :session_already_set, only: [:new, :create]

    def index
        redirect_to '/'
    end
 
    def new 
        @client = Client.new
    end 
 
    def create 
        @client = Client.new(client_params)
        if @client.save 
            session[:client_id] = @client.id
            redirect_to @client
        else 
            flash[:message] = "Invalid registration info, please try again"
            render :new 
        end 
    end

    def show 
        @client = Client.find_by_id(params[:id])
        if current_client != @client
            redirect_to '/'
        end 
    end 

    private

    def client_params
        params.require('client').permit(:first_name, :last_name, :password, :phone, :email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @client} %>

<%= render 'layouts/main_login_container'%>
    <h4 class="card-title mt-3 text-center">Register</h4>
        <p class="text-center">Get started with your account</p>
            
        <%= form_for :client do %>
            <%= render 'layouts/div_form_group'%>
                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                </div>
                    <input id="client_first_name" name="client[first_name]" class="form-control" placeholder="First name" type="text">
                </div>
            <%= render 'layouts/div_form_group'%>
                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                </div>
                    <input id="client_last_name" name="client[last_name]" class="form-control" placeholder="Last name" type="text">
                </div> 
             <%= render 'layouts/div_form_group'%>
                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                </div>
                    <input id="client_email" name="client[email]" class="form-control" placeholder="Email address" type="email">
                </div>
            <%= render 'layouts/div_form_group'%>
                    <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
                </div>
                <select class="custom-select" style="max-width: 120px;">
                    <option selected="">+1</option>
                    <option value="1">+876</option>
                </select>
                    <input id="client_phone" name="client[phone]" class="form-control" placeholder="Phone number" type="number">
                </div> 
            <%= render 'layouts/div_form_group'%>
                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                </div>
                    <input id="client_password" name="client[password]"class="form-control" placeholder="Create password" type="password">
                </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Register Account  </button>
            </div>    
            <p class="text-center">Have an account? <%= link_to "Login", login_path %></p>                                                                 
            <% end %>
<%= render 'layouts/main_container_footer'%>

app/views/clients/show.html.erb
    <%= content_tag :div, class:"col-md-9" do %>
        <%= render 'layouts/flash_message' %>
    <% end %>
  
    <%= render 'layouts/main_container'%>
        <h2 class="card-title mt-3 text-center"><%= current_client.first_name %></h2>
            <h3><%= display_appointments %></h3>
                <ul>
                    <% @client.appointments.earliest_time.each do |appointment| %>
                        <li><%= link_to appointment.treatment.title, client_appointment_path(@client,appointment) %></li>
                    <% end %>
                </ul>
            <br><br>
        <h5 class="card-title mt-3 text-center">We are looking forward to servicing you!!!</h5>
            <div class="container mt-5">
                <div class="row">
                    <div class="col-lg-4">
                        <a class="btn btn-secondary" <%= link_to "Book a New Appointment »", new_appointment_path %></a>
                    </div>
                </div>
            </div>
    <%= render 'layouts/main_container_footer'%>