config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'

  get '/most_popular_treatment/treatments/:id', to: 'treatments#show', as: 'most_popular_treatment'
 
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients, except: [:edit, :update, :destroy] do
    resources :appointments
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews, only: [:index]
  end
  
  resources :reviews, only: [:index, :new, :create] #shallow: true

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  
  belongs_to :client
  belongs_to :treatment
  has_many :reviews, dependent: :destroy
  has_many :clients, through: :reviews

  validates :treatment, :desired_time, :desired_date, presence: true

  accepts_nested_attributes_for :client, :reviews

  validate :desired_date_cannot_be_in_the_past

  def desired_date_cannot_be_in_the_past
    if desired_date.present? && desired_date < Date.today
    errors.add(:desired_date, "can't be in the past")
    end
  end 
  
  def self.earliest_time
    group(:desired_date)
  end 
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_action :login_required

  def index    
    #binding.pry
    @appointments = current_client.appointments
  end

  def show
    @appointment = current_client.appointments.find_by(id:params[:id])
    if !@appointment
      flash[:alert] = "Appointment not found."
      redirect_to client_appointments_path(@client)
    end
  end

  def new 
    @appointment = Appointment.new 
  end 

  def create 
    @appointment = current_client.appointments.build(appointment_params)
    if @appointment.save 
      redirect_to @appointment
    else 
      render :new 
    end 
  end 

  def edit
    if current_client
      @appointment = current_client.appointments.find_by(id:params[:id])
      redirect_to client_appointments_path(@client) if !@appointment
    else
      redirect_to clients_path, alert: "Client not found"
    end
  end

  def update 
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    if @appointment.save
      redirect_to @appointment
    else
      render :edit
    end
  end 
  
  def destroy 
    if @appointment = current_client.appointments.find_by_id(params[:id])
      @appointment.destroy
      redirect_to client_appointments_path(current_client) 
    else 
      flash[:error] = "The appointment could not be deleted." 
      redirect_to root_path
    end
  end
    
  private 

  def appointment_params
    params.require('appointment').permit(:special_request, :desired_time, :desired_date, :client_id, :treatment_id)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

    def display_appointments 
        if @client.appointments.empty?
            content_tag(:h5, link_to('No appointments yet - Book an Appointment here', new_appointment_path))
        else
            client = @client == current_client ? 'You have' : "#{@client.first_name}'s"
            content_tag(:h4, "#{client} #{pluralize(@client.appointments.count, 'booked Appointments')}:")
        end
    end

    def last_updated(appointment)
        appointment.updated_at.strftime("Last updated on %A, %B %d, %Y, at %I:%M %p")
    end

    def display_date(d)
        d.strftime('%A, %B %d, %Y')
    end
    
    def display_time(d)
        d.strftime('%I:%M %p')
    end
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>

<br><br>
<%= f.label :desired_date %>
<%= f.date_field :desired_date, required:true %>

<br><br>
<%= f.label :desired_time %>
<%= f.time_field :desired_time, required:true %>


<br><br>
<%= f.label :treatment %>
<%= f.collection_select :treatment_id, Treatment.all, :id, :title %> 

<br><br>
<%= f.label :special_request %>
<%= f.text_field :special_request %>

<br><br>
<%= f.submit 'request appointment' %>
<% end %>

app/views/appointments/edit.html.erb
<%= render 'layouts/main_container'%>
    <h3 class="card-title mt-3 text-center">Edit Appointment Details</h3>
                
    <%= render partial: "layouts/errors", locals: {object: @appointment} %>
    <%= render partial: "form" %>

<%= render 'layouts/main_container_footer'%>

app/views/appointments/index.html.erb
    <% if current_client %>
		  <%= render 'layouts/main_container'%>
                <h2 class="card-title mt-3 text-center">Upcoming Appointments for <%= current_client.first_name %></h2>
                    <ul>
                            <% current_client.appointments.earliest_time.each do |appointment| %>
                        <li>
                            <%= link_to appointment.treatment.title, appointment_path(appointment)%> 
                        </li>
                            <% end %>
                        <br><br>
                        <h5 class="card-title mt-3 text-center">We are looking forward to servicing you!!!</h5>
                    </ul>
                    <div class="container mt-5">
                        <div class="row">
                            <div class="col-lg-4">
                                <a class="btn btn-secondary" <%= link_to "Book a New Appointment »", new_client_appointment_path %></a>
                            </div>
                        </div>
                    </div>
                <%= render 'layouts/main_container_footer'%>
    <% end %>

app/views/appointments/new.html.erb
<%= render 'layouts/main_container'%>
    <h3 class="card-title mt-3 text-center">Request Appointment</h3>

        <%= render partial: "layouts/errors", locals: {object: @appointment} %>
        <%= render partial: "form", locals: {appointment: @appointment} %>

<%= render 'layouts/main_container_footer'%>

app/views/appointments/show.html.erb
<%= render partial: "layouts/errors", locals: {object: @appointment} %>

        <%= render 'layouts/main_container'%>
            <h2 class="card-title mt-3 text-center">Appointment Details</h2>
            <ul>
                <h4><%= @appointment.treatment.title %></h4>
                <h5><%= @appointment.desired_date.strftime("on %b/%d/%Y") %></h5>
                <h5><%= @appointment.desired_time.strftime("at %I:%M%p") %> </h5>
                <h5><%= @appointment.special_request %></h5> <br>
                <p><%= last_updated @appointment %></p>
                <br><br>
                <h5 class="card-title mt-3 text-center">We are looking forward to servicing you!!!</h5>
            </ul>   
        <%= render 'layouts/main_container_footer'%>

<div class="container mt-3">
    <% if @appointment.client == current_client %>
        <h6>
        <%= link_to "Edit Appointment", edit_appointment_path(@appointment)%> |
        <%= link_to "Delete Appointment", @appointment, method: :delete, data: { confirm: "Are you sure?" } %>
        </h6>
    <% end %>
</div>