config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'

  get '/most_popular_treatment/treatments/:id', to: 'treatments#show', as: 'most_popular_treatment'
 
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients, except: [:edit, :update, :destroy] do
    resources :appointments
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews, only: [:index]
  end
  
  resources :reviews, only: [:index, :new, :create] #shallow: true

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_div_form_group.html.erb
<div class="form-group input-group">
    <div class="input-group-prepend">

app/views/layouts/_errors.html.erb
    <% if object.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
            <% end %>
          </ul>
      </div>
    <% end %>

app/views/layouts/_flash_message.erb
<% if flash[:error] %>
    <div class="alert alert-danger" >
        <%=flash[:error]%>
    </div>
<% end %>

<% if flash[:success] %>
    <div class="alert alert-success">
        <%=flash[:success]%>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
    
    <div class="footer-copyright expand-lgpy-5 w-100">
        <div class="container text-center">
            Oasis © <%=Date.today.year%>
        </div>
    </div>

app/views/layouts/_main_container.html.erb
    <div class="container mt-5">
        <div style="background: url(<%= asset_path('blue_bg.jpg') %>)" class="page-holder bg-cover">
            <article class="card-body mx-auto" style="max-width: 400px max-height: 800px;">

app/views/layouts/_main_container_footer.html.erb
        </article>
      </div>
    </div>

app/views/layouts/_main_login_container.html.erb
<div class="container mt-5">
    <div class="card bg-info">
        <article class="card-body mx-auto" style="max-width: 400px;">

app/views/layouts/_navigation_bar.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">Oasis</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    <% if !is_logged_in? %>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/register">Register</a>
                    </li>  
                    <li class="nav-item">
                        <a href="/auth/google_oauth2" class="btn btn-block btn-google"><i class="fab fa-google"></i></a>
                    </li>
                </ul>
            </div>
        </div> 
    </nav>   
        <% else %>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" <%= link_to "Appointments", client_appointments_path(current_client) %></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" <%= link_to "Treatments", treatments_path %></a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link" <%= link_to "New Appointment", new_client_appointment_path(current_client) %></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" <%= link_to "Reviews", reviews_path %></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"<%= link_to('Logout', logout_path, method: :delete) %></a>
                    </li>
                </ul>
            </div> 
        </nav>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Oasis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link href="carousel.css" rel="stylesheet">
  </head>
    <body>
      <%= render 'layouts/navigation_bar' %>
        <br><br><br>

        <%= content_tag :div, class:"col-lg-5 col-xl-6" do %>
          <%= render 'layouts/flash_message' %>
        <% end %>

    <%= yield %>

        <br><br>
   
        <%= content_tag :footer, class:footer_class do %>
          <%= render 'layouts/footer' %>
        <% end %>
        
  </body>
</html>